CREATE TABLE `nse_stock_data` (
	`name` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`industry` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`symbol` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`series` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`instrumentKey` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`indexName` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`change5min` DECIMAL(10,2) NULL DEFAULT NULL,
	`change15min` DECIMAL(10,2) NULL DEFAULT NULL,
	`change30min` DECIMAL(10,2) NULL DEFAULT NULL,
	`changeHour` DECIMAL(10,2) NULL DEFAULT NULL,
	`changeDay` DECIMAL(10,2) NULL DEFAULT NULL,
	`changeWeek` DECIMAL(10,2) NULL DEFAULT NULL,
	`changeMonth` DECIMAL(10,2) NULL DEFAULT NULL,
	`changeYear` DECIMAL(10,2) NULL DEFAULT NULL,
	`volume` BIGINT(19) NULL DEFAULT NULL,
	`issueSize` DECIMAL(30,6) NULL DEFAULT NULL,
	`marketCap` DECIMAL(30,6) NULL DEFAULT NULL,
	`price` DECIMAL(30,6) NULL DEFAULT NULL,
	`lastUpdated` TIMESTAMP NULL DEFAULT NULL
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;
